python3-flask-web/app/__init__.py
"""
主文件
"""
from flask import Flask, render_template
from app.manager import db
import app.config
from app.article_management.views import index
from app.utils import interval

app = Flask(__name__)
# 装载配置文件
app.config.from_object(config)

# flask_sqlalchemy绑定app
db.init_app(app)

# 注册自定义过滤器
env = app.jinja_env
env.filters['interval'] = interval
# 注册蓝图
app.register_blueprint(index, url_prefix='/index')


# 自定义错误模板
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_server_error(error):
    return render_template('500.html'), 500

python3-flask-web/app/article_management/views.py
from flask import render_template, Blueprint, session, request, redirect, url_for
from app.manager import db
from app.utils import login_required, md5str, interval
from app.article_management.domain import UserLogin, Article, ArticleComment
from app.constants import PER_PAGE

index = Blueprint('index', __name__)


@index.route('/', methods=['GET', 'POST'])
def home():
    context = {}
    page = request.args.get('page', 1, type=int)  # 页码
    search_code = request.form.get('search_code') if request.form.get('search_code') else request.args.get('search_code')
    # 模糊查询db.or_:or, db.and_:and
    if search_code:
        pagination = Article.query.filter(db.or_(Article.arTitle.ilike('%'+search_code+'%'),
                                          Article.arContent.ilike('%'+search_code+'%'))).\
            order_by(db.desc(Article.create_time)).paginate(page, per_page=PER_PAGE)
    else:
        pagination = Article.query.order_by(db.desc(Article.create_time)).paginate(page, per_page=PER_PAGE)
    result = pagination.items  # 获取分页对象中的查询结果
    context['articles'] = result
    context['pagination'] = pagination
    context['search_code'] = search_code
    return render_template('index.html', **context)


@index.route('/login', methods=['GET', 'POST'])
def to_login():
    if request.method == 'GET':
        # 此处将目标路径反转函数传到模板
        return render_template('login.html', from_url_fun=request.args.get('from_url_fun'))
    else:
        username = request.form.get('username')
        password = request.form.get('password')
        remember = request.form.get('remember')
        from_url_fun = request.form.get('from_url_fun')  # 目标路径反转函数
        userlogin = UserLogin.query.filter(UserLogin.username == username, UserLogin.password == md5str(password)).first()
        if userlogin:
            session["user_id"] = userlogin.id + userlogin.username
            if remember == '1':
                session.permanent = True
            if from_url_fun is not None and from_url_fun != 'None':
                if from_url_fun.find('|') == -1:
                    return redirect(url_for('index.' + from_url_fun))
                else:
                    from_url_list = from_url_fun.split('|')
                    target_id_name = from_url_list[1]
                    values = {
                        target_id_name: from_url_list[2]
                    }
                    return redirect(url_for('index.'+from_url_list[0], **values))
            else:
                return redirect(url_for('index.home'))
        else:
            context = {
                "message": "用户名或密码错误!",
                "username": username
            }
            return render_template('login.html', **context)


@index.route('/regist', methods=['GET', 'POST'])
def to_regist():
    if request.method == 'GET':
        return render_template('regist.html')
    else:
        context = {}
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        context['username'] = username
        if password1 != password2:
            context['message'] = "两次密码输入不一致!"
            return render_template('regist.html', **context)
        else:
            new_user_login = UserLogin(username=username, password=md5str(password1))
            try:
                db.session.add(new_user_login)
                db.session.commit()
                return redirect(url_for('index.to_login'))
            except:
                db.session.rollback()
                context['message'] = "注册失败!!"
                return render_template('regist.html', **context)


@index.route('/login_out', methods=['GET', 'POST'])
def login_out():
    session.pop('user_id', None)
    return redirect(url_for('index.home'))


@index.route('/to_add_article', methods=['GET', 'POST'])
@login_required('to_add_article')
def to_add_article():
    if request.method == 'GET':
        return render_template('article_management/article.html')
    else:
        context = {}
        arTitle = request.form.get('arTitle')
        arContent = request.form.get('arContent')
        authorId = interval(session.get('user_id'), end=36)
        new_article = Article(arTitle=arTitle, arContent=arContent, authorId=authorId)
        context['arTitle'] = arTitle
        context['arContent'] = arContent
        try:
            db.session.add(new_article)
            db.session.commit()
            context['message'] = '发布成功!'
        except:
            db.session.rollback()
            context['message'] = '发布失败!'
        return render_template('article_management/article.html', **context)


@index.route('/detail/<article_id>', methods=['GET', 'POST'])
# @login_required('to_article_detail', target_id_name='article_id')
def to_article_detail(article_id):
    context = {}
    page = request.args.get('page', 1, type=int)  # 页码
    article_detail = Article.query.get(article_id)
    pagination = ArticleComment.query.filter(ArticleComment.articleId == article_id).\
        order_by(db.desc(ArticleComment.create_time)).paginate(page, per_page=PER_PAGE)
    result = pagination.items  # 获取分页对象中的查询结果
    context['article_detail'] = article_detail
    context['comments'] = result
    context['pagination'] = pagination
    return render_template('article_management/article_detail.html', **context)


@index.route('/comment/<article_id>', methods=['POST'])
@login_required('to_article_detail', target_id_name='article_id')
def to_add_comment(article_id):
    authorId = interval(session.get('user_id'), end=36)
    acContent = request.form.get('acContent')
    new_article_comment = ArticleComment(acContent=acContent, articleId=article_id, authorId=authorId)
    try:
        db.session.add(new_article_comment)
        db.session.commit()
    except:
        db.session.rollback()
    return redirect(url_for('index.to_article_detail', article_id=article_id))

python3-flask-web/app/templates/_macros.html
{# Jinja2 宏的参数列表中不用加入**kwargs 即可接收关键字参数。
    分页宏把接收到的所有关键字参数都传给了生成分页链接的url_for() 方法。#}
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

python3-flask-web/app/templates/article_management/article.html
{% extends 'layout.html' %}
{% block title %}发布文章{% endblock %}

{% block head %}
    <link href="{{url_for('static', filename='css/article_management/article.css')}}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="main">
        <h3 class="articleTitle">发布文章</h3>
        <form class="form-container" id="loginform" name="loginform" method="post" action="{{ url_for('index.to_add_article') }}">
            <div class="form-group">
                <input type="text" id="arTitle" name="arTitle" class="form-control" placeholder="标题" value="{{ arTitle }}" required autofocus>
            </div>
            <div class="form-group">
                <textarea class="form-control" rows="10" cols="20" id="arContent" name="arContent" placeholder="请输入内容" required>{{ arContent }}</textarea>
            </div>
            <div>
                <span class="message">{{ message }}</span>
            </div>
            <button id="button" class="btn btn-primary " type="submit">立即发布</button>
        </form>
    </div>
{% endblock %}

python3-flask-web/app/templates/article_management/article_detail.html
{% extends 'layout.html' %}
{% import '_macros.html' as macros %}
{% block title %}文章详情{% endblock %}

{% block head %}
    <link href="{{url_for('static', filename='css/article_management/article_detail.css')}}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="main">
        <h3 class="article-title">{{ article_detail.arTitle }}</h3>
        <p class="article-info">
            <span>作者: {{ article_detail.author.username }}</span>
            <span>时间: {{ article_detail.create_time }}</span>
        </p>
        <hr>
        <p class="article-content">{{ article_detail.arContent }}</p>
        <hr>
        <h4>评论({{ comments|length }}):</h4>
        <form method="post" action="{{ url_for('index.to_add_comment', article_id=article_detail.id) }}">
            <div class="form-group">
                <input type="text" name="acContent" class="form-control" placeholder="请输入评论">
            </div>
            <div class="form-group form-button">
                <button id="button" class="btn btn-primary" type="submit">立即评论</button>
            </div>
        </form>
        <ul class="comment-list">
            {% for comment in comments%}
                <li>
                    <div class="comment-info">
                        <img class="avatar" src="{{url_for('static', filename='images/ChinaDragon.jpg')}}">
                        <span class="comment-author">{{ comment.author.username }}</span>
                        <span class="comment-time">{{ comment.create_time }}</span>
                    </div>
                <p class="comment">{{ comment.acContent }}</p>
                </li>
            {% endfor %}
        </ul>
        {% if pagination %}
            <nav style="text-align: center">
                <div class="pagination">
                    {{ macros.pagination_widget(pagination, 'index.to_article_detail', article_id=article_detail.id) }}
                </div>
            </nav>
        {% endif %}
    </div>
{% endblock %}

python3-flask-web/app/templates/index.html
{% extends 'layout.html' %}
{% import '_macros.html' as macros %}
{% block title %}首页{% endblock %}

{% block head %}
    <link href="{{url_for('static', filename='css/index.css')}}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="main">
        <ul class="article-list-group">
            {% for article in articles %}
                <li>
                    <div class="avatar-group">
                        <img class="avatar" src="{{url_for('static', filename='images/ChinaDragon.jpg')}}">
                    </div>
                    <div class="article-group">
                        <p class="article-title"><a href="{{ url_for('index.to_article_detail',article_id=article.id)}}">{{ article.arTitle }}</a></p>
                        <p class="article-content">{{ article.arContent }}</p>
                        <p class="article-info">
                            <span class="article-author">{{ article.author.username }}</span>
                            <span class="article-time">{{ article.create_time }}</span>
                        </p>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% if pagination %}
            <nav style="text-align: center">
                <div class="pagination">
                    {{ macros.pagination_widget(pagination, 'index.home', search_code=search_code) }}
                </div>
            </nav>
        {% endif %}
    </div>
{% endblock %}

python3-flask-web/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-ChinaDragon</title>
    <link href="{{url_for('static', filename='js/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='js/bootstrap/css/bootstrap-select.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='css/style.css')}}" rel="stylesheet">
    <script src="{{url_for('static', filename='js/jquery/jquery-1.11.3.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap/js/bootstrap-select.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap/js/defaults-zh_CN.min.js')}}"></script>
    <script type=text/javascript>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand alogo" href="#">
              <img class="logo" src="{{url_for('static', filename='images/ChinaDragon.jpg')}}">
          </a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('index.home') }}">首页</a></li>
            <li><a href="{{ url_for('index.to_add_article') }}">发布问答</a></li>
          </ul>
          <form class="navbar-form navbar-left" method="post" action="{{ url_for('index.home') }}">
            <div class="form-group">
              <input type="text" name="search_code" class="form-control" placeholder="请输入关键词">
            </div>
            <button type="submit" class="btn btn-default">查询</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if session.get('user_id') %}
                  {#此处引用自定义过滤器对储存的userid + username进行截断处理,因为userid默认是uuid 36位,所以此处写死37#}
                  <li><a href="#">{{ session.get('user_id')|interval(37) }}</a></li>
                  <li><a href="{{ url_for('index.login_out') }}">注销</a></li>
              {% else %}
                  <li><a href="{{ url_for('index.to_login') }}">登录</a></li>
                  <li><a href="{{ url_for('index.to_regist') }}">注册</a></li>
              {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    {% block body %}{% endblock %}
</body>
</html>

python3-flask-web/app/templates/login.html
{% extends 'layout.html' %}
{% block title %}登录{% endblock %}

{% block head %}
    <link href="{{url_for('static', filename='css/login_regist.css')}}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="main">
        <h3 class="logintitle">欢迎登陆</h3>
        <form class="form-container" id="loginform" name="loginform" method="post" action="{{ url_for('index.to_login') }}">
            <div class="form-group input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                <input type="text" name="username" class="form-control" placeholder="用户名" value="{{ username }}" required autofocus>
            </div>
            <div class="form-group input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                <input type="password" name="password" class="form-control" placeholder="密码" required>
            </div>
            {#<div class="row">
                <div class="col-md-8">
                    <input type="text" id="kaptchaCode" name="kaptchaCode" class="form-control" placeholder="请输入验证码" required>
                </div>
                <img src="Kaptcha.jpg" id="kaptcha" alt="验证码">
                <a href="javascript:changeImg()">换一张</a>
            </div>#}
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="remember" value="1"> 下次自动登录
                </label>
            </div>
            <div>
                <span class="message">{{ message }}</span>
            </div>
            <input type="hidden" name="from_url_fun" value="{{ from_url_fun }}">
            <button id="button" class="btn btn-primary btn-block" type="submit">立即登录</button>
        </form>
    </div>
{% endblock %}

python3-flask-web/app/templates/regist.html
{% extends 'layout.html' %}
{% block title %}注册{% endblock %}

{% block head %}
    <link href="{{url_for('static', filename='css/login_regist.css')}}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="main">
        <h3 class="logintitle">注册</h3>
        <form class="form-container" id="loginform" name="loginform" method="post" action="{{ url_for('index.to_regist') }}">
            <div class="form-group input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                <input type="text" id="username" name="username" class="form-control" placeholder="用户名" value="{{ username }}" required autofocus>
            </div>
            <div class="form-group input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                <input type="password" name="password1" class="form-control" placeholder="密码" required>
            </div>
            <div class="form-group input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                <input type="password" name="password2" class="form-control" placeholder="确认密码" required>
            </div>
            <div>
                <span class="message">{{ message }}</span>
            </div>
            <button id="button" class="btn btn-primary btn-block" type="submit">立即注册</button>
        </form>
    </div>
{% endblock %}